import type { Metadata } from "next";
import { Ubuntu_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import {
  ClerkProvider,
} from '@clerk/nextjs'


const ubuntuMono = Ubuntu_Mono({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-ubuntuMono"
});

export const metadata: Metadata = {
  title: "Kesheng's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider appearance={{
        elements: {
          card: "bg-uk-background-primary-light",
          footerAction: "text-uk-blue-light hover:text-uk-blue-dark",
        }
      }}>
        <body className={`${ubuntuMono.variable} `}>
          <Header />
          <main >{children}</main>
          <Footer/>
        </body>
      </ClerkProvider>
    </html>
  );
}